### ISSUE TITLE
回傳空 array 

### ISSUE THREAD

**Issue by chilijung** [fukuball/CKIPClient-PHP#1]
我照著範例做，也申請了一個帳號。但是他回傳是空的 array 請問可能是哪些原因呢？謝謝！

**Comment by paullo0106** [comment]
@chilijung 可以附上你的程式碼嗎? 哪隻程式在哪個狀況下會回傳空array?

**Comment by ghost** [comment]
已解決～當初應該是key尚未通過,謝謝

2014-11-30 23:19 GMT+08:00 Paul Lo notifications@github.com:

> @chilijung https://github.com/chilijung 可以附上你的程式碼嗎? 哪隻程式在哪個狀況下會回傳空array?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fukuball/CKIPClient-PHP/issues/1#issuecomment-64988375
> .

## 

王喻正 Yu-Cheng Wang
yuzheng.wang@gmail.com
